
from machine import Pin
from umqtt.simple import MQTTClient
import NeoPixelLib
np = NeoPixelLib.NeoPixel(Pin(19),128)
from machine import I2C
from ssd1306 import SSD1306_I2C
i2cbus = I2C(scl=Pin(22),sda=Pin(21),freq=400000)
oled = SSD1306_I2C(128,64,i2cbus)
button=Pin(32,Pin.IN)
RED=(255,0,0)
GREEN=(0,255,0)
BLUE=(0,0,255)

YELLOW=(255,255,0)
CYAN=(0,255,255)
MAGENTA=(255,0,255)
WHITE=(255,255,255)
SSID="thananat   2.4G"
PASSWORD="0891550015"

SERVER= "mqtt.eclipse.org"  #  "137.135.83.217"
server_port = 1883
CLIENT_ID = "EnET-group01"
TOPIC = b"/OpenKB-19/pin18/set"
username=''
password=''
c=None



counter = 0
n=0
import LibHR2
def inter(e):
  time.sleep_ms(20)
  if button.value()==0:
    global counter
    counter+=1
    print(counter)
button.irq(trigger=Pin.IRQ_FALLING,handler=inter)
def connect_wifi(ssid,pwd):
  import network
  import time  
  counter = 0  
  global sta_if,ap_if
  sta_if = network.WLAN(network.STA_IF)  
  sta_if.active(True)
 #cfg=('192.168.31.219','255.255.255.0','192.168.31.1','8.8.8.8')
 #sta_if.ifconfig(cfg)
  
  sta_if.connect(ssid,pwd)
  while not sta_if.isconnected() and counter < 10 :
    counter += 1
    print(".",end="")
    time.sleep(1)
  if sta_if.isconnected():
    print("Connected my IP :",sta_if.ifconfig()[0])
    return True

  else:
    print("Connection fail !")
    return False
connect_wifi("thananat   2.4G","0891550015")
import urequests , ujson
np.brightness=0.01
while True:
  bct = urequests.get('http://worldtimeapi.org/api/timezone/Asia/Bangkok')
  bct_js = bct.json()
  us_rate=bct_js['datetime']
  s=str(us_rate)  
  ss=s[11:19]
  print(ss)
  x=s[15]
  y=s[15]
  np.clear()
  if(s[11]=='0'):
    hd0()
    if(s[12]=='0'):
      hr0()
    elif(s[12]=='1'):
      hr1()
    elif(s[12]=='2'): 
      hr2() 
    elif(s[12]=='3'): 
      hr3()
    elif(s[12]=='4'): 
      hr4() 
    elif(s[12]=='5'): 
      hr5() 
    elif(s[12]=='6'): 
      hr6() 
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 

          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 

          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      
    elif(s[12]=='7'):
      hr7() 
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):

          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
    elif(s[12]=='8'): 
      hr8()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
    elif(s[12]=='9'): 
      hr9()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    

        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
  elif(s[11]=='1'):   
    hd1()    
    if(s[12]=='0'):
      hr0()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
    elif(s[12]=='1'):
      hr1()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
    elif(s[12]=='2'): 
      hr2()  
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
    elif(s[12]=='3'): 
      hr3()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
    elif(s[12]=='4'): 
      hr4() 
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 

          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 

          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    

        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
    elif(s[12]=='5'): 
      hr5()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 

        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 

        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
    elif(s[12]=='6'): 
      hr6() 
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      
    elif(s[12]=='7'):
      hr7()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()        
    elif(s[12]=='8'): 
      hr8()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 

        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 

        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
      
    elif(s[12]=='9'): 
      hr9()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 

          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
  elif(s[11]=='2'):   
    hd2()
    if(s[12]=='0'):
      hr0()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):

          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
    elif(s[12]=='1'):
      hr1()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
    elif(s[12]=='2'): 
      hr2()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    

        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    

        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
    elif(s[12]=='3'): 
      hr3()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
  else:
    np.clear()
    np.write()   
  np.write()
  oled.fill(0)
  oled.text('{0}'.format(ss),2,2)  
  oled.show()
  
  while(x==y):
    bct = urequests.get('http://worldtimeapi.org/api/timezone/Asia/Bangkok')
    bct_js = bct.json()
    us_rate=bct_js['datetime']
    s=str(us_rate)
    ss=s[11:19]
    y=s[15]
    oled.fill(0)
    print(ss)
    oled.text('{0}'.format(ss),2,2)  
    oled.show()
    
    if(counter==1):
      RED=GREEN
      if(n==0):
        x=555
        n=1
    if(counter==2):
      RED=BLUE
      if(n==1):
        x=555
        n=2
    if(counter==3):
      RED=YELLOW
      if(n==2):
        x=555
        n=3
    if(counter==4):
      RED=CYAN
      if(n==3):
        x=555
        n=4  
    if(counter==5):
      RED=MAGENTA
      if(n==4):
        x=555
        n=5
    if(counter==6):
      RED=WHITE
      if(n==5):
        x=555
        n=6        
    if(counter>6):
    
      RED=(255,0,0)
      counter=0
      if(n==6):
        x=555
        n=0          
   

   
    time.sleep(0.1)
    bct.close()   
  bct.close()
  def sub_cb(topic, msg):
    print((topic, msg))
    if msg == b"on":
      counter==1
      n=1
      c.publish("/OpenKB-19/pin18/status",'red')
      print("red")
    elif msg == b"off":
      counter==2
      n=2
      c.publish("/OpenKB-19/pin18/status",'GREEN')
      print("green")
    else:
      c.publish("/OpenKB-19/pin18/status",'red')
  try:
    connectWifi(SSID,PASSWORD)
    server=SERVER
    c = MQTTClient(CLIENT_ID, server,server_port)     #create a mqtt client
    c.set_callback(sub_cb)                    #set callback
    c.connect()                               #connect mqtt
    c.subscribe(TOPIC)                        #client subscribes to a topic
    print("Connected to %s, subscribed to %s topic" % (server, TOPIC))

    while True:
      c.wait_msg()                            #wait message 

  finally:
      if(c is not None):
          c.disconnect()
      wlan.disconnect()
      wlan.active(False)  












