
from machine import Pin
import NeoPixelLib
np = NeoPixelLib.NeoPixel(Pin(19),128)
from machine import I2C
from ssd1306 import SSD1306_I2C
sw1=Pin(0,Pin.IN)
i2cbus = I2C(scl=Pin(22),sda=Pin(21),freq=400000)
oled = SSD1306_I2C(128,64,i2cbus)
a=255
b=0
c=0
RED=(a,b,c)
BLACK=(0,0,0)
BLUE=(0,0,255)
import LibHR2


def connect_wifi(ssid,pwd):
  import network
  import time  
  counter = 0  
  global sta_if,ap_if
  sta_if = network.WLAN(network.STA_IF)  
  sta_if.active(True)
 #cfg=('192.168.31.219','255.255.255.0','192.168.31.1','8.8.8.8')
 #sta_if.ifconfig(cfg)
  
  sta_if.connect(ssid,pwd)
  while not sta_if.isconnected() and counter < 10 :
    counter += 1
    print(".",end="")
    time.sleep(1)
  if sta_if.isconnected():
    print("Connected my IP :",sta_if.ifconfig()[0])
    return True

  else:
    print("Connection fail !")
    return False
connect_wifi("thananat   2.4G","0891550015")
import urequests , ujson
np.brightness=0.01
while True:
  bct = urequests.get('http://worldtimeapi.org/api/timezone/Asia/Bangkok')
  bct_js = bct.json()
  us_rate=bct_js['datetime']
  s=str(us_rate)  
  ss=s[11:19]
  print(ss)
  x=s[15]
  y=s[15]
  np.clear()
  if(s[11]=='0'):
    hd0()
    if(s[12]=='0'):
      hr0()
    elif(s[12]=='1'):
      hr1()
    elif(s[12]=='2'): 
      hr2() 
    elif(s[12]=='3'): 
      hr3()
    elif(s[12]=='4'): 
      hr4() 
    elif(s[12]=='5'): 
      hr5() 
    elif(s[12]=='6'): 
      hr6() 
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 

          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 

          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      
    elif(s[12]=='7'):
      hr7() 
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):

          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
    elif(s[12]=='8'): 
      hr8()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
    elif(s[12]=='9'): 
      hr9()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    

        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
  elif(s[11]=='1'):   
    hd1()    
    if(s[12]=='0'):
      hr0()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
    elif(s[12]=='1'):
      hr1()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
    elif(s[12]=='2'): 
      hr2()  
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
    elif(s[12]=='3'): 
      hr3()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
    elif(s[12]=='4'): 
      hr4() 
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 

          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 

          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    

        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
    elif(s[12]=='5'): 
      hr5()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 

        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 

        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
    elif(s[12]=='6'): 
      hr6() 
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      
    elif(s[12]=='7'):
      hr7()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()        
    elif(s[12]=='8'): 
      hr8()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 

        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 

        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
      
    elif(s[12]=='9'): 
      hr9()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 

          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()              
  elif(s[11]=='2'):   
    hd2()
    if(s[12]=='0'):
      hr0()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):

          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
    elif(s[12]=='1'):
      hr1()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
    elif(s[12]=='2'): 
      hr2()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    

        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    

        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
    elif(s[12]=='3'): 
      hr3()
      if(s[14]=='0'):
        np0()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='1'):   
        np1()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()
      elif(s[14]=='2'):   
        np2()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()  
      elif(s[14]=='3'):   
        np3()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9() 
      elif(s[14]=='4'):   
        np4()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
      elif(s[14]=='5'):   
        np5()
        if(s[15]=='0'):
          mp0()
        elif(s[15]=='1'):
          mp1()
        elif(s[15]=='2'): 
          mp2()   
        elif(s[15]=='3'): 
          mp3()
        elif(s[15]=='4'): 
          mp4() 
        elif(s[15]=='5'): 
          mp5()    
        elif(s[15]=='6'): 
          mp6()      
        elif(s[15]=='7'):
          mp7()    
        elif(s[15]=='8'): 
          mp8()    
        elif(s[15]=='9'): 
          mp9()       
  else:
    np.clear()
    np.write()   
  np.write()
  oled.fill(0)
  oled.text('{0}'.format(ss),2,2)  
  oled.show()
  while(x==y):
    if(sw1==0):
      b=255
      x=555
    bct = urequests.get('http://worldtimeapi.org/api/timezone/Asia/Bangkok')
    bct_js = bct.json()
    us_rate=bct_js['datetime']
    s=str(us_rate)
    ss=s[11:19]
    y=s[15]
    oled.fill(0)
    print(ss)
    oled.text('{0}'.format(ss),2,2)  
    oled.show()
    time.sleep(0.5)
    bct.close()   
  bct.close()
  











